// Build script for the OPC UA crate
// Reads CSV schema file and generates Rust code accordingly
use std::fs;
use std::io::{self, BufRead, Write};

fn upper_snake_case(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        if c.is_uppercase() {
            if !result.is_empty() {
                result.push('_');
            }
            result.push(c);
        } else {
            result.push(c.to_ascii_uppercase());
        }
    }
    result.replace("__", "_")
}

struct StatusCode {
    name: String,
    value: u32,
    explanation: String,
}

fn parse_codes(csv_path: &str) -> Vec<StatusCode> {
    println!("Parsing CSV file: {}", csv_path);
    let csv = io::BufReader::new(fs::File::open(csv_path).unwrap());
    let mut codes = Vec::with_capacity(253);

    for line in csv.lines() {
        let line = line.unwrap();
        let sep1 = line.find(',').unwrap();
        let sep2 = line[sep1 + 1..].find(',').unwrap() + sep1 + 1;

        let name = line[0..sep1].to_string();

        let value_str = &line[sep1 + 1..sep2];
        let value = if value_str.starts_with("0x") {
            u32::from_str_radix(&value_str[2..], 16).unwrap()
        } else {
            value_str.parse::<u32>().unwrap()
        };

        let explanation_str = &line[sep2 + 1..];
        let explanation = if explanation_str.starts_with('"') && explanation_str.ends_with('"') {
            explanation_str[1..explanation_str.len() - 1].to_string()
        } else {
            explanation_str.to_string()
        };
        codes.push(StatusCode {
            name,
            value,
            explanation,
        });
    }
    codes
}

fn generate_status_code_rs(codes: &[StatusCode], output_path: &str) {
    let mut rs = std::fs::File::create(output_path).unwrap();
    writeln!(rs, "// This file is automatically generated. Do not edit.").unwrap();

    writeln!(rs, "").unwrap();
    for status in codes {
        writeln!(rs, "/// {}", status.explanation).unwrap();
        writeln!(
            rs,
            "pub const {}: u32 = 0x{:08X};",
            upper_snake_case(&status.name),
            status.value
        )
        .unwrap();
    }

    writeln!(rs, "").unwrap();
    writeln!(rs, "#[allow(non_camel_case_types)]").unwrap();
    writeln!(rs, "#[derive(Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(rs, "#[repr(u32)]").unwrap();
    writeln!(rs, "pub enum StatusCode {{").unwrap();
    for status in codes {
        writeln!(rs, "    /// {}", status.explanation).unwrap();
        writeln!(rs, "    {} = 0x{:08X},", status.name, status.value).unwrap();
    }
    writeln!(rs, "}}").unwrap();

    writeln!(rs, "").unwrap();
    writeln!(rs, "impl StatusCode {{").unwrap();
    writeln!(rs, "    pub fn code(&self) -> u32 {{").unwrap();
    writeln!(rs, "        *self as u32").unwrap();
    writeln!(rs, "    }}").unwrap();
    writeln!(rs, "").unwrap();
    writeln!(rs, "    pub fn name(&self) -> &'static str {{").unwrap();
    writeln!(rs, "        match self {{").unwrap();
    for status in codes {
        writeln!(rs, "            StatusCode::{} => \"{}\",", status.name, status.name).unwrap();
    }
    writeln!(rs, "        }}").unwrap();
    writeln!(rs, "    }}").unwrap();
    writeln!(rs, "").unwrap();
    writeln!(rs, "    pub fn explanation(&self) -> &'static str {{").unwrap();
    writeln!(rs, "        match self {{").unwrap();
    for status in codes {
        writeln!(rs, "            StatusCode::{} => \"{}\",", status.name, status.explanation).unwrap();
    }
    writeln!(rs, "        }}").unwrap();
    writeln!(rs, "    }}").unwrap();
    writeln!(rs, "}}").unwrap();

    writeln!(rs, "").unwrap();
    writeln!(rs, "impl From<u32> for StatusCode {{").unwrap();
    writeln!(rs, "    fn from(code: u32) -> Self {{").unwrap();
    writeln!(rs, "        match code {{").unwrap();
    for status in codes {
        writeln!(rs, "            0x{:08X} => StatusCode::{},", status.value, status.name).unwrap();
    }
    writeln!(rs, "            _ => panic!(\"Unknown status code: 0x{{:08X}}\", code),").unwrap();
    writeln!(rs, "        }}").unwrap();
    writeln!(rs, "    }}").unwrap();
    writeln!(rs, "}}").unwrap();
}

// fn generate_ua_error_rs(codes: &[StatusCode], output_path: &str) {
//     let mut rs = std::fs::File::create(output_path).unwrap();
//     writeln!(rs, "// This file is automatically generated. Do not edit.").unwrap();

//     writeln!(rs, "").unwrap();
//     writeln!(rs, "#[allow(non_camel_case_types)]").unwrap();
//     writeln!(rs, "#[derive(Clone, Copy, PartialEq, Eq)]").unwrap();
//     writeln!(rs, "pub enum UaError {{").unwrap();
//     for status in codes.iter().filter(|status| !status.name.starts_with("Good")) {
//         writeln!(rs, "    /// {}", status.explanation).unwrap();
//         writeln!(rs, "    {} = 0x{:08X},", status.name, status.value).unwrap();
//     }
//     writeln!(rs, "}}").unwrap();

//     writeln!(rs, "").unwrap();
//     writeln!(rs, "impl UaError {{").unwrap();
//     writeln!(rs, "    pub fn code(&self) -> u32 {{").unwrap();
//     writeln!(rs, "        *self as u32").unwrap();
//     writeln!(rs, "    }}").unwrap();
//     writeln!(rs, "").unwrap();
//     writeln!(rs, "    pub fn explanation(&self) -> &'static str {{").unwrap();
//     writeln!(rs, "        match self {{").unwrap();
//     for status in codes.iter().filter(|status| !status.name.starts_with("Good")) {
//         writeln!(rs, "            UaError::{} => \"{}\",", status.name, status.explanation).unwrap();
//     }
//     writeln!(rs, "        }}").unwrap();
//     writeln!(rs, "    }}").unwrap();
//     writeln!(rs, "}}").unwrap();

//     writeln!(rs, "").unwrap();
//     writeln!(rs, "impl std::fmt::Display for UaError {{").unwrap();
//     writeln!(rs, "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{").unwrap();
//     writeln!(rs, "        write!(f, \"{{:?}}\", self)").unwrap();
//     writeln!(rs, "    }}").unwrap();
//     writeln!(rs, "}}").unwrap();

//     writeln!(rs, "").unwrap();
//     writeln!(rs, "impl std::fmt::Debug for UaError {{").unwrap();
//     writeln!(rs, "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{").unwrap();
//     writeln!(rs, "        write!(f, \"{{:?}}\", self)").unwrap();
//     writeln!(rs, "    }}").unwrap();
//     writeln!(rs, "}}").unwrap();
// }

fn main() {
    println!("cargo:rerun-if-changed=schema/StatusCode.csv");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let csv_path = "schema/StatusCode.csv";
    let status_code_path = format!("{}/status_code.rs", out_dir);
    // let ua_error_path = format!("{}/ua_error.rs", out_dir);

    let codes = parse_codes(csv_path);

    println!("Generating Rust code at: {}", status_code_path);
    generate_status_code_rs(&codes, &status_code_path);

    // println!("Generating Rust code at: {}", ua_error_path);
    // generate_ua_error_rs(&codes, &ua_error_path);
}
