//! TypeScript code generation utilities for OPC/UA.
use crate::opc_bsd;
use tokio::io::{self, AsyncWriteExt};

pub async fn generate_ts_types<W>(types: &opc_bsd::TypeDictionary, out: &mut W) -> io::Result<()>
where
    W: io::AsyncWrite + Unpin,
{
    out.write("// module generated by ua-nsc\n".as_bytes())
        .await?;
    if let Some(doc) = &types.doc {
        module_doc_comment(doc, out).await?;
    }

    // Include built-in TypeScript types.
    builtin_types(out).await?;

    for type_def in &types.types {
        // Generate TypeScript definitions for each type here.
        generate_type_def(type_def, out).await?;
    }

    Ok(())
}

async fn module_doc_comment<W>(doc: &str, out: &mut W) -> io::Result<()>
where
    W: io::AsyncWrite + Unpin,
{
    out.write("/**\n".as_bytes()).await?;
    for line in doc.lines() {
        out.write(format!(" * {}\n", line).as_bytes()).await?;
    }
    out.write(" * @module\n".as_bytes()).await?;
    out.write(" */\n".as_bytes()).await?;
    Ok(())
}

async fn doc_comment<W>(doc: &str, out: &mut W) -> io::Result<()>
where
    W: io::AsyncWrite + Unpin,
{
    out.write("/**\n".as_bytes()).await?;
    for line in doc.lines() {
        out.write(format!(" * {}\n", line).as_bytes()).await?;
    }
    out.write(" */\n".as_bytes()).await?;
    Ok(())
}

async fn builtin_types<W>(out: &mut W) -> io::Result<()>
where
    W: io::AsyncWrite + Unpin,
{
    let builtins_code = include_str!("builtins.ts");
    out.write(builtins_code.as_bytes()).await?;
    Ok(())
}

fn remove_namespace(type_name: &str) -> &str {
    let idx = type_name.find(':');
    if let Some(idx) = idx {
        &type_name[idx + 1..]
    } else {
        type_name
    }
}

const BUILTIN_TYPES: &[&str] = &[
    "Boolean",
    "SByte",
    "Byte",
    "Int16",
    "UInt16",
    "Int32",
    "UInt32",
    "Int64",
    "UInt64",
    "Float",
    "Double",
    "String",
    "DateTime",
    "Guid",
    "ByteString",
    "XmlElement",
    "NodeId",
    "ExpandedNodeId",
    "StatusCode",
    "QualifiedName",
    "LocalizedText",
    "ExtensionObject",
    "DataValue",
    "Variant",
    "DiagnosticInfo",
];

const EXCLUDED_TYPES: &[&str] = &[
    "NodeIdType",
    "TwoByteNodeId",
    "FourByteNodeId",
    "NumericNodeId",
    "StringNodeId",
    "GuidNodeId",
    "ByteStringNodeId",
];

fn excluded_type(type_name: &str) -> bool {
    let type_name = remove_namespace(type_name);
    BUILTIN_TYPES.contains(&type_name) || EXCLUDED_TYPES.contains(&type_name)
}

async fn generate_type_def<W>(type_def: &opc_bsd::Type, out: &mut W) -> io::Result<()>
where
    W: io::AsyncWrite + Unpin,
{
    match type_def {
        opc_bsd::Type::Opaque { desc, .. } => {
            if excluded_type(&desc.name) {
                return Ok(());
            }
            out.write("\n".as_bytes()).await?;
            if let Some(doc) = &desc.doc {
                doc_comment(doc, out).await?;
            }
            out.write(format!("export type {} = ByteString;\n", desc.name).as_bytes())
                .await?;
        }
        opc_bsd::Type::Enumerated { desc, values, .. } => {
            generate_enumeration(desc, values, out).await?;
        }
        opc_bsd::Type::Structured { desc, base_type, fields } => {
            if excluded_type(&desc.name) {
                return Ok(());
            }
            out.write("\n".as_bytes()).await?;
            if let Some(doc) = &desc.doc {
                doc_comment(doc, out).await?;
            }
            let extends = if let Some(base_type) = base_type {
                format!(" extends {}", remove_namespace(base_type))
            } else {
                String::new()
            };
            out.write(format!("export interface {}{} {{\n", desc.name, extends).as_bytes())
                .await?;
            for field in fields {
                let name = &field.name;
                let Some(type_name) = &field.type_name else {
                    continue;
                };
                out.write(format!("    {}: {};\n", name, remove_namespace(type_name)).as_bytes())
                    .await?;
            }
            out.write("}\n".as_bytes()).await?;
        }
    }
    Ok(())
}

async fn generate_enumeration<W>(
    desc: &opc_bsd::TypeDescription,
    values: &[opc_bsd::EnumValue],
    out: &mut W,
) -> io::Result<()>
where
    W: io::AsyncWrite + Unpin,
{
    if excluded_type(&desc.name) {
        return Ok(());
    }
    out.write("\n".as_bytes()).await?;
    if let Some(doc) = &desc.doc {
        doc_comment(doc, out).await?;
    }
    let type_name = remove_namespace(&desc.name);
    let mut compact_def = String::new();
    let mut first = true;
    for value in values {
        if let (Some(name), Some(value)) = (&value.name, &value.value) {
            let compact_name = format!("{}_{}", type_name, name).to_uppercase();
            out.write(format!("export const {} = {};\n", &compact_name, value).as_bytes())
                .await?;
            if !first {
                compact_def.push_str(" | ");
            }
            first = false;

            compact_def.push_str(&format!("{}", value));
        }
    }
    if compact_def.is_empty() {
        return Ok(());
    }
    out.write(format!("export type {} = {};\n", desc.name, compact_def).as_bytes())
        .await?;
    Ok(())
}
